// Generates src/abi.ts from the Foundry artifacts (run `forge build` in contracts/ first).
// The router's ABI also carries the events and errors of its linked libraries and of the SwapVM / Aqua code it
// runs, so that viem can decode every revert a trade can produce. CI regenerates the file and fails on a diff.
//   node scripts/gen_abi.ts [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const out = (p: string) => fileURLToPath(new URL(`../../contracts/out/${p}`, import.meta.url));
type Item = { type: string; name?: string; inputs?: { type: string }[] };
const abiOf = (file: string, name: string): Item[] => JSON.parse(readFileSync(out(`${file}/${name}.json`), "utf8")).abi;
const only = (items: Item[], ...types: string[]) => items.filter((i) => types.includes(i.type));

function merge(...lists: Item[][]): Item[] {
  const seen = new Set<string>();
  const res: Item[] = [];
  for (const i of lists.flat()) {
    const key = `${i.type}:${i.name ?? ""}(${(i.inputs ?? []).map((x) => x.type).join(",")})`;
    if (!seen.has(key)) {
      seen.add(key);
      res.push(i);
    }
  }
  return res;
}

const tradeErrors = merge(
  only(abiOf("CorrFiEngine.sol", "CorrFiEngine"), "error", "event"),
  only(abiOf("CorrFiOrders.sol", "CorrFiOrders"), "error", "event"),
  only(abiOf("CorrFiCurve.sol", "CorrFiCurve"), "error"),
  only(abiOf("CorrFiVault.sol", "CorrFiVault"), "error"),
  only(abiOf("IAqua.sol", "IAqua"), "error"),
  only(abiOf("Controls.sol", "Deadline"), "error"),
  only(abiOf("TakerTraits.sol", "TakerTraitsLib"), "error"),
  only(abiOf("MakerTraits.sol", "MakerTraitsLib"), "error"),
);

const abis: Record<string, Item[]> = {
  hubAbi: abiOf("CorrFiHub.sol", "CorrFiHub"),
  routerAbi: merge(abiOf("CorrFiRouter.sol", "CorrFiRouter"), tradeErrors),
  lensAbi: merge(abiOf("CorrFiLens.sol", "CorrFiLens"), tradeErrors),
  vaultAbi: abiOf("CorrFiVault.sol", "CorrFiVault"),
  tokenAbi: abiOf("CorrFiToken.sol", "CorrFiToken"),
  aquaAbi: abiOf("Aqua.sol", "Aqua"),
  erc20Abi: abiOf("IERC20Metadata.sol", "IERC20Metadata"),
  testUsdcAbi: abiOf("TestUSDC.sol", "TestUSDC"),
};

let src = "// Generated by scripts/gen_abi.ts from contracts/out — do not edit.\n";
for (const [name, abi] of Object.entries(abis)) src += `\nexport const ${name} = ${JSON.stringify(abi)} as const;\n`;

const target = fileURLToPath(new URL("../src/abi.ts", import.meta.url));
if (process.argv.includes("--check")) {
  const cur = readFileSync(target, "utf8");
  if (cur !== src) {
    console.error("src/abi.ts is stale: run `node scripts/gen_abi.ts` after `forge build`");
    process.exit(1);
  }
  console.log("src/abi.ts is up to date");
} else {
  writeFileSync(target, src);
  console.log(`src/abi.ts: ${Object.keys(abis).length} ABIs`);
}
