// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {CorrFiMath} from "../src/lib/CorrFiMath.sol";
import {CorrFiCurve} from "../src/lib/CorrFiCurve.sol";
import {FixedPointMathLib} from "solady/utils/FixedPointMathLib.sol";

/// @notice Bit-exact agreement with the shared vectors generated by the Python port (vectors/gen_fixedpoint.py).
contract FixedPointVectorsTest is Test {
    string internal json;

    function setUp() public {
        json = vm.readFile(string.concat(vm.projectRoot(), "/../vectors/fixedpoint.json"));
    }

    function _s(string memory key) internal view returns (string[] memory) {
        return vm.parseJsonStringArray(json, key);
    }

    function _u(string memory s) internal pure returns (uint256) {
        return vm.parseUint(s);
    }

    function _i(string memory s) internal pure returns (int256) {
        return vm.parseInt(s);
    }

    function _isRevert(string memory s) internal pure returns (bool) {
        return keccak256(bytes(s)) == keccak256("revert");
    }

    function _table() internal view returns (uint256[10] memory t) {
        string[] memory v = _s(".meta.table");
        for (uint256 i; i < 10; ++i) t[i] = _u(v[i]);
    }

    // ------------------------------------------------------------------ F1

    function test_lnWad() public view {
        string[] memory x = _s(".ln_wad.x");
        string[] memory y = _s(".ln_wad.y");
        for (uint256 i; i < x.length; ++i) {
            assertEq(this.lnWadExt(int256(_u(x[i]))), _i(y[i]), x[i]);
        }
    }

    /// R §7.3: 10,000 random inputs (vectors/lnwad_bulk.json).
    function test_lnWadBulk() public view {
        string memory bulk = vm.readFile(string.concat(vm.projectRoot(), "/../vectors/lnwad_bulk.json"));
        string[] memory x = vm.parseJsonStringArray(bulk, ".x");
        string[] memory y = vm.parseJsonStringArray(bulk, ".y");
        assertEq(x.length, 10_000);
        for (uint256 i; i < x.length; ++i) {
            assertEq(FixedPointMathLib.lnWad(int256(_u(x[i]))), _i(y[i]));
        }
    }

    function lnWadExt(int256 x) external pure returns (int256) {
        return FixedPointMathLib.lnWad(x);
    }

    function test_logRatio() public view {
        string[] memory p0 = _s(".log_ratio.p0");
        string[] memory p1 = _s(".log_ratio.p1");
        string[] memory r = _s(".log_ratio.r");
        for (uint256 i; i < p0.length; ++i) {
            assertEq(CorrFiMath.logRatio(_u(p0[i]), _u(p1[i])), _i(r[i]));
        }
    }

    // ------------------------------------------------------------------ F2-F5

    function test_accumulate() public view {
        string[] memory c = _s(".accumulate.c");
        string[] memory va = _s(".accumulate.va");
        string[] memory vb = _s(".accumulate.vb");
        string[] memory ra = _s(".accumulate.ra");
        string[] memory rb = _s(".accumulate.rb");
        string[] memory cs = _s(".accumulate.cs");
        string[] memory c2 = _s(".accumulate.c2");
        string[] memory va2 = _s(".accumulate.va2");
        string[] memory vb2 = _s(".accumulate.vb2");
        for (uint256 i; i < c.length; ++i) {
            int256 k = _i(cs[i]);
            (int256 oc, uint256 oa, uint256 ob) = CorrFiMath.accumulate(
                _i(c[i]), _u(va[i]), _u(vb[i]), CorrFiMath.winsorize(_i(ra[i]), k), CorrFiMath.winsorize(_i(rb[i]), k)
            );
            assertEq(oc, _i(c2[i]));
            assertEq(oa, _u(va2[i]));
            assertEq(ob, _u(vb2[i]));
        }
    }

    function test_settle() public {
        string[] memory c = _s(".settle.c");
        string[] memory va = _s(".settle.va");
        string[] memory vb = _s(".settle.vb");
        string[] memory nv = _s(".settle.nv");
        string[] memory nmin = _s(".settle.nmin");
        string[] memory rho = _s(".settle.rho");
        string[] memory l = _s(".settle.l");
        string[] memory isVoid = _s(".settle.void");
        for (uint256 i; i < c.length; ++i) {
            if (_isRevert(rho[i])) {
                vm.expectRevert(CorrFiMath.ZeroVariance.selector);
                this.rhoExt(_i(c[i]), _u(va[i]), _u(vb[i]));
            } else {
                assertEq(CorrFiMath.rho(_i(c[i]), _u(va[i]), _u(vb[i])), _i(rho[i]));
            }
            (uint256 ol, bool ov) = CorrFiMath.longT(_i(c[i]), _u(va[i]), _u(vb[i]), _u(nv[i]), _u(nmin[i]));
            assertEq(ol, _u(l[i]));
            assertEq(ov ? 1 : 0, _u(isVoid[i]));
        }
    }

    function rhoExt(int256 c, uint256 va, uint256 vb) external pure returns (int256) {
        return CorrFiMath.rho(c, va, vb);
    }

    function test_payout() public view {
        string[] memory ql = _s(".payout.ql");
        string[] memory qs = _s(".payout.qs");
        string[] memory l = _s(".payout.l");
        string[] memory pay = _s(".payout.pay");
        string[] memory res = _s(".payout.res");
        for (uint256 i; i < ql.length; ++i) {
            assertEq(CorrFiMath.payout(_u(ql[i]), _u(qs[i]), _u(l[i])), _u(pay[i]));
            assertEq(CorrFiMath.reserve(_u(ql[i]), _u(qs[i]), _u(l[i])), _u(res[i]));
        }
    }

    // ------------------------------------------------------------------ F7-F11

    function test_fairValue() public {
        string[] memory c = _s(".fair_value.c");
        string[] memory va = _s(".fair_value.va");
        string[] memory vb = _s(".fair_value.vb");
        string[] memory nobs = _s(".fair_value.nobs");
        string[] memory n = _s(".fair_value.n");
        string[] memory sab = _s(".fair_value.sab");
        string[] memory sa2 = _s(".fair_value.sa2");
        string[] memory sb2 = _s(".fair_value.sb2");
        string[] memory p = _s(".fair_value.p");
        for (uint256 i; i < c.length; ++i) {
            if (_isRevert(p[i])) {
                vm.expectRevert(CorrFiMath.ZeroVariance.selector);
                this.fairValueExt(
                    _i(c[i]), _u(va[i]), _u(vb[i]), _u(nobs[i]), _u(n[i]), _i(sab[i]), _u(sa2[i]), _u(sb2[i])
                );
            } else {
                assertEq(
                    CorrFiMath.fairValue(
                        _i(c[i]), _u(va[i]), _u(vb[i]), _u(nobs[i]), _u(n[i]), _i(sab[i]), _u(sa2[i]), _u(sb2[i])
                    ),
                    _u(p[i])
                );
            }
        }
    }

    function fairValueExt(
        int256 c,
        uint256 va,
        uint256 vb,
        uint256 nobs,
        uint256 n,
        int256 sab,
        uint256 sa2,
        uint256 sb2
    ) external pure returns (uint256) {
        return CorrFiMath.fairValue(c, va, vb, nobs, n, sab, sa2, sb2);
    }

    function test_sigmaPAndH0() public view {
        uint256[10] memory table = _table();
        string[] memory t = _s(".sigma_p.t");
        string[] memory sp = _s(".sigma_p.sp");
        string[] memory h0 = _s(".sigma_p.h0");
        for (uint256 i; i < t.length; ++i) {
            assertEq(CorrFiMath.sigmaP(_u(t[i]), table), _u(sp[i]));
            assertEq(CorrFiMath.h0(_u(t[i]), table, 15e16, 5e15), _u(h0[i]));
        }
    }

    function test_sigmaBarAndHO() public view {
        string[] memory sig2 = _s(".sigma_bar.sig2");
        string[] memory dp = _s(".sigma_bar.dp");
        string[] memory dk = _s(".sigma_bar.dk");
        string[] memory lam = _s(".sigma_bar.lam");
        string[] memory upd = _s(".sigma_bar.upd");
        string[] memory age = _s(".sigma_bar.age");
        string[] memory co = _s(".sigma_bar.co");
        string[] memory ho = _s(".sigma_bar.ho");
        for (uint256 i; i < sig2.length; ++i) {
            assertEq(CorrFiMath.sigmaBar2Update(_u(sig2[i]), _i(dp[i]), _u(dk[i]), _u(lam[i])), _u(upd[i]));
            assertEq(CorrFiMath.hO(_u(age[i]), _u(sig2[i]), _u(co[i])), _u(ho[i]));
        }
    }

    function test_risk() public view {
        string[] memory q = _s(".risk.q");
        string[] memory p = _s(".risk.p");
        string[] memory rc = _s(".risk.rc");
        string[] memory rb = _s(".risk.rb");
        string[] memory u = _s(".risk.u");
        string[] memory hu = _s(".risk.hu");
        for (uint256 i; i < q.length; ++i) {
            uint256 r = CorrFiMath.riskCapital(_i(q[i]), _u(p[i]));
            assertEq(r, _u(rc[i]));
            assertEq(CorrFiMath.hU(_u(u[i]), 2e16, 6e17, 9e17), _u(hu[i]));
        }
        // utilization of Σ RC = m · rc (m recorded by the generator)
        string[] memory m = _s(".risk.m");
        for (uint256 i; i < q.length; ++i) {
            assertEq(CorrFiMath.utilization(_u(rc[i]) * _u(m[i]), _u(rb[i])), _u(u[i]));
        }
    }

    // ------------------------------------------------------------------ F16-F18

    /// @dev Columns of the "curve" section, parsed once (re-parsing the JSON per case runs out of gas).
    struct CurveCols {
        string[] p;
        string[] h;
        string[] hmin;
        string[] kq;
        string[] qmax;
        string[] q0;
        string[] q;
        string[] x;
        string[] payD1;
        string[] receiveD2;
        string[] payD3;
        string[] receiveD4;
        string[] qtyD1;
        string[] qtyD3;
        string[] qtyD2;
        string[] qtyD4;
    }

    function test_curve() public view {
        CurveCols memory v;
        v.p = _s(".curve.p");
        v.h = _s(".curve.h");
        v.hmin = _s(".curve.hmin");
        v.kq = _s(".curve.kq");
        v.qmax = _s(".curve.qmax");
        v.q0 = _s(".curve.q0");
        v.q = _s(".curve.q");
        v.x = _s(".curve.x");
        v.payD1 = _s(".curve.pay_d1");
        v.receiveD2 = _s(".curve.receive_d2");
        v.payD3 = _s(".curve.pay_d3");
        v.receiveD4 = _s(".curve.receive_d4");
        v.qtyD1 = _s(".curve.qty_d1");
        v.qtyD3 = _s(".curve.qty_d3");
        v.qtyD2 = _s(".curve.qty_d2");
        v.qtyD4 = _s(".curve.qty_d4");
        for (uint256 i; i < v.p.length; ++i) {
            _checkCurveCase(v, i);
        }
    }

    function _checkCurveCase(CurveCols memory v, uint256 i) internal view {
        CorrFiCurve.Curve memory c =
            CorrFiCurve.make(_u(v.p[i]), _u(v.h[i]), _u(v.hmin[i]), _u(v.kq[i]), _u(v.qmax[i]));
        int256 q0 = _i(v.q0[i]);
        uint256 q = _u(v.q[i]);
        uint256 x = _u(v.x[i]);
        assertEq(CorrFiCurve.payD1(c, q0, q), _u(v.payD1[i]));
        assertEq(CorrFiCurve.receiveD2(c, q0, q), _u(v.receiveD2[i]));
        assertEq(CorrFiCurve.payD3(c, q0, q), _u(v.payD3[i]));
        assertEq(CorrFiCurve.receiveD4(c, q0, q), _u(v.receiveD4[i]));
        assertEq(CorrFiCurve.qtyD1ExactIn(c, q0, x), _u(v.qtyD1[i]));
        assertEq(CorrFiCurve.qtyD3ExactIn(c, q0, x), _u(v.qtyD3[i]));
        _checkSell(c, q0, x, v.qtyD2[i], true);
        _checkSell(c, q0, x, v.qtyD4[i], false);
    }

    function _checkSell(CorrFiCurve.Curve memory c, int256 q0, uint256 x, string memory want, bool long_)
        internal
        view
    {
        if (_isRevert(want)) {
            try this.sellExt(c, q0, x, long_) returns (uint256) {
                revert("expected BookTooThin");
            } catch (bytes memory err) {
                assertEq(bytes4(err), CorrFiCurve.BookTooThin.selector);
            }
        } else {
            assertEq(this.sellExt(c, q0, x, long_), _u(want));
        }
    }

    function sellExt(CorrFiCurve.Curve memory c, int256 q0, uint256 x, bool long_) external pure returns (uint256) {
        return long_ ? CorrFiCurve.qtyD2ExactOut(c, q0, x) : CorrFiCurve.qtyD4ExactOut(c, q0, x);
    }
}
